### ISSUE TITLE
How do PCMBase.Threshold.Skip.Singular and PCMBase.Skip.Singular work?

### ISSUE THREAD

**Issue by krzbar** [venelin/PCMBase#5]
I am experimenting with phylogenies with 0 branch lengths and it seems that PCMBase.Threshold.Skip.Singular and PCMBase.Skip.Singular do not skip these branches somehow:

library(PCMBase)
library(ape)
RNGversion(min(as.character(getRversion()),"3.6.1"))
set.seed(12345, kind = "Mersenne-Twister", normal.kind = "Inversion")
phyltree<-ape::rtree(30)
phyltree$edge.length[c(10,11)]<-0
BMparams<-list(vX0=matrix(0,nrow=2,ncol=1),Sxx=rbind(c(1,5),c(0,1)))
tmpdata<-matrix(rnorm(60),ncol=2)
modelBM <- PCM(model = "BM", k = 2)
modelBM$X0[]<-BMparams$vX0[,1]
modelBM$Sigma_x[,,1]<-BMparams$Sxx
res1<-PCMLik(t(tmpdata),phyltree,modelBM)

min_bl<-0.001
pcmbase_min_bl<-PCMBase::PCMOptions()$PCMBase.Threshold.Skip.Singular
new_min_bl_use<-max(c(pcmbase_min_bl,min_bl))
options(PCMBase.Threshold.Skip.Singular=new_min_bl_use)
options(PCMBase.Skip.Singular=TRUE)
res2<-PCMLik(t(tmpdata),phyltree,modelBM)

Both res1 and res2 have NA likelihood values and errors, while I would understand that in res2's case as the threshold for skipping and skipping are set, then a likelihood values should be obtained?

(using CRAN's PCMBase 1.2.11 )

Best wishes
Krzysztof

**Comment by venelin** [comment]
One of the 0-length branches in your tree is pointing to a tip. Branches pointing to tips cannot be skipped.
